package com.devson.nosved.util

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import java.io.File

object CookieExtractor {
    private const val COOKIE_HEADER = "# Netscape HTTP Cookie File\n# Auto-generated by Nosved built-in WebView\n\n"

    fun extractAndSaveCookies(context: Context): Int {
        val dbFile = File(context.dataDir, "app_webview/Default/Cookies")
        val fallbackFile = File(context.dataDir, "app_webview/Cookies")
        val sourceFile = when {
            dbFile.exists() -> dbFile
            fallbackFile.exists() -> fallbackFile
            else -> return 0
        }

        val tempFile = File(context.cacheDir, "temp_cookies_db")
        try {
            sourceFile.inputStream().use { input ->
                tempFile.outputStream().use { output ->
                    input.copyTo(output)
                }
            }

            val db = SQLiteDatabase.openDatabase(
                tempFile.absolutePath,
                null,
                SQLiteDatabase.OPEN_READONLY
            )

            val cursor = db.query(
                "cookies",
                arrayOf("host_key", "path", "is_secure", "expires_utc", "name", "value"),
                null, null, null, null, null
            )

            val sb = java.lang.StringBuilder(COOKIE_HEADER)
            var count = 0

            val hostIndex = cursor.getColumnIndex("host_key")
            val pathIndex = cursor.getColumnIndex("path")
            val secureIndex = cursor.getColumnIndex("is_secure")
            val expiryIndex = cursor.getColumnIndex("expires_utc")
            val nameIndex = cursor.getColumnIndex("name")
            val valueIndex = cursor.getColumnIndex("value")

            while (cursor.moveToNext()) {
                val hostKey = if (hostIndex >= 0) cursor.getString(hostIndex) ?: "" else ""
                val path = if (pathIndex >= 0) cursor.getString(pathIndex) ?: "/" else "/"
                val isSecure = if (secureIndex >= 0) cursor.getInt(secureIndex) == 1 else true
                val expiresUtc = if (expiryIndex >= 0) cursor.getLong(expiryIndex) else 0L
                val name = if (nameIndex >= 0) cursor.getString(nameIndex) ?: "" else ""
                val value = if (valueIndex >= 0) cursor.getString(valueIndex) ?: "" else ""

                if (hostKey.isEmpty() || name.isEmpty()) continue

                val host = if (!hostKey.startsWith(".")) ".$hostKey" else hostKey
                val includeSubdomains = hostKey.startsWith(".") || hostKey.contains(".")

                sb.append(host).append("\t")
                    .append(includeSubdomains.toString().uppercase()).append("\t")
                    .append(path).append("\t")
                    .append(isSecure.toString().uppercase()).append("\t")
                    .append(expiresUtc).append("\t")
                    .append(name).append("\t")
                    .append(value).append("\n")

                count++
            }
            cursor.close()
            db.close()

            val destFile = File(context.filesDir, "cookies.txt")
            destFile.writeText(sb.toString())
            return count
        } catch (e: Exception) {
            e.printStackTrace()
            return 0
        } finally {
            if (tempFile.exists()) {
                tempFile.delete()
            }
        }
    }

    fun getCookiesFileCount(context: Context): Int {
        val destFile = File(context.filesDir, "cookies.txt")
        if (!destFile.exists()) return 0
        var count = 0
        try {
            destFile.forEachLine { line ->
                if (line.isNotBlank() && !line.startsWith("#")) {
                    count++
                }
            }
        } catch (_: Exception) {}
        return count
    }
}
